Updated dependencies and migrated to th2 gradle plugin
th2-net/th2-codec-avro pull request #19
Opened 2024-04-29 07:42 UTC by Nikita-Smirnov-Exactpro

2024-04-29 08:16 UTC, OptimumCode approved these changes

2024-04-29 08:27 UTC, Nikita-Smirnov-Exactpro commented
I completed my changes, @OptimumCode could you please review to finalize PR

2024-04-29 08:59 UTC, OptimumCode approved these changes

2024-04-29 09:02 UTC, OptimumCode requested changes
Something is wrong with maven signing
```
Execution failed for task ':signMavenJavaPublication'.
> Error while evaluating property 'signatory' of task ':signMavenJavaPublication'.
   > Could not read PGP secret key
```

2024-04-29 09:19 UTC, OptimumCode requested changes

2024-04-29 09:19 UTC, OptimumCode commented on .github/workflows/build-release.yml
> +    secrets:
issue: You should pass signing secrets as well

2024-04-29 15:11 UTC, OptimumCode requested changes
Please, update workflow branch to main

2024-04-29 15:22 UTC, OptimumCode approved these changes

2024-05-01 08:39 UTC, OptimumCode approved these changes

2024-05-01 11:21 UTC, merged